version: 1.0

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - npm ci --prefer-offline
      - npm run build
      - php artisan migrate --force -n
      - php artisan db:seed --force -n
      - php artisan optimize:clear
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

  recurring:
    excludes:
      - tests
      - node_modules
      - storage
    pre-deployment-remote-commands:
      - php artisan down
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - npm ci --prefer-offline
      - npm run build
      - php artisan migrate --force -n
      - php artisan db:seed --force -n
      - php artisan optimize:clear
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

    runtime:
      cron-jobs:
        - command: php artisan schedule:run
          schedule: "* * * * *"
